local map = vim.keymap.set

map('n', '<leader>g', function()
  Snacks.picker.git_status()
end, { desc = 'Git status' })
map('n', '<leader>gs', function()
  Snacks.picker.git_status()
end, { desc = 'Git status' })
map('n', '<leader>gl', function()
  Snacks.picker.git_log()
end, { desc = 'Git log' })
map('n', '<leader>gL', function()
  Snacks.picker.git_log_line()
end, { desc = 'Git log current line' })
map('n', '<leader>gf', function()
  Snacks.picker.git_log_file()
end, { desc = 'Git log current file' })
map('n', '<leader>gd', function()
  Snacks.picker.git_diff()
end, { desc = 'Git diff hunks' })
map('n', '<leader>gb', function()
  Snacks.picker.git_branches()
end, { desc = 'Git branches' })
map('n', '<leader>gS', function()
  Snacks.picker.git_stash()
end, { desc = 'Git stash' })
map('n', '<leader>g/', function()
  Snacks.picker.git_grep()
end, { desc = 'Git grep' })
map('n', '<leader>gp', function()
  Snacks.picker.gh_pr()
end, { desc = 'GitHub pull requests' })
map('n', '<leader>gi', function()
  Snacks.picker.gh_issue()
end, { desc = 'GitHub issues' })
map('n', '<leader>ga', function()
  Snacks.picker.gh_actions()
end, { desc = 'GitHub actions' })
map('n', '<leader>gD', function()
  Snacks.picker.gh_diff()
end, { desc = 'GitHub diff' })
