#!/usr/bin/env sh

CONFIG_DIR="${CONFIG_DIR:-$(cd "$(dirname "$0")" && pwd)}"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

. "$CONFIG_DIR/colors.sh"

sketchybar --bar \
  position=top \
  topmost=off \
  height=30 \
  color="$BAR_BG" \
  corner_radius=9 \
  margin=30 \
  y_offset=0 \
  padding_left=12 \
  padding_right=12 \
  blur_radius=0

sketchybar --default \
  padding_left=3 \
  padding_right=3 \
  icon.font="Symbols Nerd Font:Regular:13.0" \
  label.font="SF Pro:Semibold:12.0" \
  icon.color="$TEXT" \
  label.color="$TEXT" \
  icon.padding_left=6 \
  icon.padding_right=3 \
  label.padding_left=3 \
  label.padding_right=6 \
  background.drawing=on \
  background.color="$ITEM_BG" \
  background.corner_radius=6 \
  background.height=19 \
  background.padding_left=2 \
  background.padding_right=2

sketchybar --add event aerospace_workspace_change \
           --add event aerospace_layout_change

. "$ITEM_DIR/left.sh"
. "$ITEM_DIR/workspaces.sh"
. "$ITEM_DIR/right.sh"

sketchybar --reorder $AEROSPACE_WORKSPACE_ITEMS aerospace.layout front_app battery volume clock calendar input memory cpu network

sketchybar --update
