[helpers]

[default]
depends = []

[default.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
zed = { target = "~/.config/zed", type = "symbolic" }
"zellij.kdl" = { target = "~/.config/zellij/config.kdl", type = "symbolic" }
"karabiner.json" = "~/.config/karabiner/karabiner.json"
".alacritty.yml" = "~/.alacritty.yml"
".starship.toml" = "~/.starship.toml"
".tmux.conf" = "~/.tmux.conf"
".gitconfig" = "~/.gitconfig"
".bashrc" = { target = "~/.bashrc", type = "symbolic" }
".bash_profile" = { target = "~/.bash_profile", type = "symbolic" }
".zshrc" = { target = "~/.zshrc", type = "symbolic" }
"ghostty" = "~/.config/ghostty/config"
"claude-settings.json" = "~/.claude/settings.json"
"moxide/settings.toml" = "~/.config/moxide/settings.toml"

[default.variables]

[settings]
default_target_type = "automatic"
