theme = "onedark"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1
auto-format = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"

[keys.normal]
g = { q = ":bc" }
C-d = ["move_line_down", "move_line_down", "move_line_down"]
C-u = ["move_line_up", "move_line_up", "move_line_up"]
